theme = "heobot"
baseurl = "http://blog.import.re"
languageCode = "ko-kr"
title = "blog.import.re"
MetaDataFormat = "toml"
paginate = 3

[params]
  author = "Jaewe Heo"
  nickname = "importre"
  aboutme = "허재위"
  profile = "/images/importre.jpg"
  github = "importre"
  twitter = "importre"
  facebook = "importre"
  copyrightYear = "2015"
#  ga = "UA-44364795-2"
