theme = "heobot"
baseurl = "http://blog.import.re"
languageCode = "ko-kr"
title = "blog.import.re"
MetaDataFormat = "yaml"
paginate = 3
disqusShortname = "blogimportre"

[params]
  author = "Jaewe Heo"
  nickname = "importre"
  aboutme = "허재위"
  description = "importre (heobot)"
  profile = "images/importre.jpg"
  github = "importre"
  twitter = "importre"
  facebook = "importre"
  copyrightYear = "2015"
  ga = "UA-64739906-2"
  fbappid = "1706988242848832"
  brandsize = "200"
